### ISSUE TITLE
Possible NuGet restore failures

### ISSUE THREAD

**Issue by loic-sharma** [openSUSE/ca-certificates#10]
Hello,

I am from the NuGet team at Microsoft. NuGet is the package manager for the .NET ecosystem, including the C# language. Network Security Services (NSS) 3.63 and newer distrusts Symantec which will cause failures when installing NuGet packages. For more information, please see: https://github.com/NuGet/Announcements/issues/56

Does openSUSE or SUSE Enterprise Linux use NSS to maintain its list of trusted root certificates? If so, does  openSUSE or SUSE Enterprise Linux have a timeline for when it will update to NSS 3.63 or newer?

If you need any additional information, feel free to reach out to me at loshar@microsoft.com.

Best,
Loic

**Comment by lnussel** [comment]
I don't know whether and when nss gets updated.  What you seem to be looking for is the root CA list though. That gets extracted from mozilla-nss and shipped as separate package (https://build.opensuse.org/package/show/openSUSE:Factory/ca-certificates-mozilla). So even if mozilla-nss itself may be at an older version, the root CA list on the distro is current in general.
