### ISSUE TITLE
ECCN – Export Control Classification Number for the product :  ca-certificates  with version 2018.1.18

### ISSUE THREAD

**Issue by kkabhi** [openSUSE/ca-certificates#5]
This is to bring in your kind notice that we are interested in your product ca-certificates  with version 2018.1.18, so we would request you to please assist us with some of our queries below : 

•	 If you have already classified this software with ECCN, please confirm the applicable number. 
 
      If you do not have your software classified with an ECCN, please kindly answer the following questions so that we may self-assess:
 
1, Does the Software perform any encryption or utilize any encryption processes?  Y/N
2. If the answer is YES to question 1, please indicate if the encryption is coded into the application or separately called (such as using SSL)
3. If the answer is YES to question 1, please indicate what function(s) the cryptography/encryption serves 
 
A, Copyright protection purposes (Includes using a license key/code)
B, User authentication purposes
C, A core part of the functionality such as to encrypt databases
D, To encrypt communications between the software and a host system.
 
Background information:
An Export Control Classification Number (ECCN) is a specific alpha-numeric code that identifies the level of export control for items e.g. software that are exported from member states of the Wassenaar Arrangement, including the United States. After obtaining the ECCN, the exporter must determine whether an export license is required to export items to certain countries.

**Comment by msmeissn** [comment]
1. N

while we convert certificates, we do not use cryptography during this transition.
